<?= $this->doctype() ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('work test project')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <!-- Scripts -->
    </head>
    <body>
        <?= $this->content ?>
    </body>
</html>
